<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Bank Manager Login"
           tests="2"
           failures="1"
           errors="0"
           skipped="0"
           time="0.269">
  <properties />
            <testcase name="bankManagerLogin1" time="0.091" classname="com.lti.testcases.LoginTest">
                <failure type="java.lang.AssertionError"
                  message="expected [false] but found [true]"
              >
<![CDATA[java.lang.AssertionError: expected [false] but found [true]
  org.testng.Assert.fail(Assert.java:110)
  org.testng.Assert.failNotEquals(Assert.java:1577)
  org.testng.Assert.assertFalse(Assert.java:78)
  org.testng.Assert.assertFalse(Assert.java:88)
  com.lti.testcases.LoginTest.bankManagerLogin1(LoginTest.java:27)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:567)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
  org.testng.TestRunner.privateRun(TestRunner.java:829)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
  org.testng.SuiteRunner.run(SuiteRunner.java:330)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
  org.testng.TestNG.runSuites(TestNG.java:1099)
  org.testng.TestNG.run(TestNG.java:1067)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="bankManagerLogin" time="0.178" classname="com.lti.testcases.LoginTest" />
      
</testsuite>
